### ISSUE TITLE
А ты уверен что все методы этого класса должны быть публичными?

### ISSUE THREAD

**Issue by boris-dev** [STRENCH0/liga-internship#12]
https://github.com/STRENCH0/liga-internship/blob/589c87411eea58722a04ca177d097092e3fdcb9e/javacore-song-task/src/main/java/ru/liga/songtask/utils/MidiAnalyzer.java#L12

**Comment by STRENCH0** [comment]
Тут не понял. У меня все методы, возвращающие конкретную информацию о файле и никак не меняющие состояние класса и файла. Зачем тогда делать приватными методы?

**Comment by boris-dev** [comment]
Окей, считаем этот класс утилитным, тут конечно большая смесь ответственностей, но в целом код хорошо разбит на методы, что далает его читабельным.
