### ISSUE TITLE
Строго говоря Tempo не всегда находится на первом треке, а ещё их может быть несколько

### ISSUE THREAD

**Issue by boris-dev** [STRENCH0/liga-internship#13]
Но ты можешь спросить закономерный вопрос - "Откуда мне было знать?"

https://github.com/STRENCH0/liga-internship/blob/589c87411eea58722a04ca177d097092e3fdcb9e/javacore-song-task/src/main/java/ru/liga/songtask/utils/MidiChanger.java#L28

**Comment by STRENCH0** [comment]
Понадеялся, что код из SimpleMidiFile по получению темпа универсальный. Исправил.
